openapi: 3.0.0
info:
  title: Auction
  version: 1.0.0
  description: "Realisation of auction system"
tags:
  - name: Authentication
  - name: Steward
  - name: Participant

paths:
  /auth/register:
    post:
      summary: Register new user in the system
      description: Choose nickname and role to use system.
      tags:
        - Authentication
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: integer
        - in: query
          name: role
          required: true
          schema:
            type: string
            enum: [steward, participant]
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message: "Successfully registered"
        '401':
          description: This nickname is already taken
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message: "user_id is already exist"

  /auth/login:
    post:
      summary: Log in with an existing account
      tags:
        - Authentication
      description: Log in using your nickname.
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '404':
          description: User is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message:
                  "No such user"

  /participant/items:
    get:
      summary: Get list of items
      tags:
        - Participant
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
                example:
                  id: 5
                  name: picture
                  price: 1220
                  owner: John
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message:
                  "Error during getting list of items"

  /participant/price:
    put:
      summary: Make new bet
      tags:
        - Participant
      parameters:
        - in: query
          name: item_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message:
                  "Price is higher now"
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message:
                  "There is no such item"


  /steward/add:
    post:
      summary: Add new item
      tags:
        - Steward
      parameters:
        - in: query
          name: item
          schema:
            $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message:
                  "Item added to the auction"
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message:
                  "This item already exist"


  /steward/stop:
    put:
      summary: Give lot to the last owner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
                example:
                  message:
                    "Steward end auction"
        '408':
          description: Request timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message:
                  "Steward lost connection"

components:
  schemas:
    Item:
      type: object
      required:
        -item_id
        -name
        -price
        -owner
      properties:
        item_id:
          type: integer
          format: uuid
        name:
          type: string
        price:
          type: integer
        owner:
          type: string

    Response:
      type: object
      required:
        - message
      properties:
        message:
          type: string
